### ISSUE TITLE
Fontify done checkbox items in org-mode

### ISSUE THREAD

**Issue by FrostyX** [Fuco1/Fuco1.github.io#17]
Hello @Fuco1,
I wasn't sure where to put feedback for your article about checkboxes

https://fuco1.github.io/2017-05-25-Fontify-done-checkbox-items-in-org-mode.html

because you don't have a comment section on your blog, so I decided to put it here.

Thank you very much for it, I was migrating from vimwiki and looking for this exact feature and I was surprised that `org-mode` doesn't support it by default. 

Personally I would love to see two improvements, so I want to suggest them here and hope that you will get bored once and hack on it :pray: 

1. I would like to have an option to write something like `[-]` to mark the item as checked out but not finished. The use-case quite typical, I write something on my checklist, and then it turns out that I don't actually need it. I still want to keep track of it, but I want it to be grayed out and not bother me
2. It would be great if everything that is below the item and indented to the right was also grayed out when the item is grayed out. This works well when you have nested checklists but if you have a checklist item and have just few notes below it, those notes will always have a normal font even though the item is finished. Example of this is 

    - [X] Give @Fuco1 feedback about awesome article about org-mode checklists
      - https://fuco1.github.io/2017-05-25-Fontify-done-checkbox-items-in-org-mode.html
      - He doesn't have comment section so write an issue on GitHub

**Comment by Fuco1** [comment]
Org mode already uses the `[-]` syntax for trees so I think that one is out of the question.

``` org
- [-] first                <-- this becomes [-] when you complete a subitem
  - [ ] children
  - [X] and                <-- toggle this to see the effect on the parent.
  - [ ] more
  - [ ] children
```

As for `2` I already hacked on it but it doesn't quite work so I haven't pushed it yet.  Basically I turned the regexp into a function and then do some org element trickery.  If you want to play with it, this is the code that I use now which should work the same as the published version.  But it's a good start :).  One day I'm sure I finish it.

```elisp
(defun my-org-fontify-done-list-item (limit)
  "Fontify a list item marked with [X] with `org-headline-done' face."
  (when (re-search-forward
         "^[ \t]*\\(?:[-+*]\\|[0-9]+[).]\\)[ \t]+\\(\\(?:\\[@\\(?:start:\\)?[0-9]+\\][ \t]*\\)?\\[\\(?:X\\|\\([0-9]+\\)/\\2\\)\\][^\n]*\\(?:\n\\|\\'\\)\\)"
         limit
         t)
    (backward-char 1)
    (-let (((_ (&plist :parent (_ (&plist :begin)) :end)) (org-element-at-point)))
      (set-match-data (list begin end))
      (goto-char end)
      t)))

(font-lock-add-keywords
 'org-mode
 `((my-org-fontify-done-list-item 0 'org-headline-done prepend))
 'append)
```

**EDIT**: so it actually works, the problem is that when you un-check the fontification isn't removed.  Also if you edit some text in the middle.  You'd have to collapse-uncollapse the node for the style to be removed.

![](https://i.imgur.com/mCqwnA8.png)

![](https://i.imgur.com/imvXzWr.png)
