### ISSUE TITLE
Support imenu in dired with dired-imenu

### ISSUE THREAD

**Issue by DamienCassou** [Fuco1/Fuco1.github.io#2]
https://melpa.org/#/dired-imenu :-)

**Comment by Fuco1** [comment]
Hm that's a bit different.  This is basically `ido-find-file` which seems a bit redundant.

**Comment by DamienCassou** [comment]
`ido-find-file` opens a file IIRC. If you just want to move point to a file, I use `dired-imenu`. This is useful when you want to manipulate filename or permissions or just check date and size and neighbor files. I have the impression your code also takes care of inserted directories. You might want to open a PR to `dired-imenu` :-).

**Comment by Fuco1** [comment]
Well, my code *only* takes care of the directories.  I have a workflow with virtual direds (I will write about that) and I use the subdirectories quite a lot.

The thing is, there already is built-in `dired-goto-file` which does exactly what you're describing.  It is bound to `j` by default.  That's why I haven't added that functionality as it is redundant.
